/* The following code was generated by JFlex 1.4.3 on 06/06/15 15:52 */

package lexico;

//import java_cup.runtime.Symbol;
//import static lexico.Simbolos.java


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 06/06/15 15:52 from the specification file
 * <tt>lexer.flex</tt>
 */
class Analizador {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\43\1\4\1\0\1\0\1\3\22\0\1\43\11\0\1\6"+
    "\1\42\3\0\1\5\12\2\3\0\1\41\3\0\32\1\6\0\1\17"+
    "\1\13\1\16\1\31\1\24\1\32\1\35\1\30\1\15\1\1\1\26"+
    "\1\14\1\34\1\25\1\23\1\11\1\1\1\22\1\20\1\21\1\12"+
    "\1\36\1\37\1\33\1\27\1\40\1\7\1\0\1\10\uff82\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\1\1\4\1\5\16\2"+
    "\1\6\1\7\1\10\1\0\10\2\1\11\23\2\1\12"+
    "\6\2\1\13\2\10\2\0\11\2\1\14\16\2\1\15"+
    "\7\2\1\16\5\2\1\17\1\2\1\0\1\10\6\2"+
    "\1\20\1\21\5\2\1\22\2\2\1\23\6\2\1\24"+
    "\1\2\1\25\3\2\1\26\1\2\1\27\13\2\1\30"+
    "\5\2\1\31\1\32\2\2\1\33\2\2\1\34\2\2"+
    "\1\35\6\2\1\36\1\37\1\40\1\41\1\42\7\2"+
    "\1\43\2\2\1\44\1\2\1\45\2\2\1\46\1\2"+
    "\1\47\1\50\2\2\1\51\1\52\1\2\1\53\10\2"+
    "\1\54\1\55\1\56\4\2\1\57\1\60\3\2\1\61"+
    "\1\2\1\62\2\2\1\63\1\2\1\64\1\65\1\2"+
    "\1\66\1\2\1\67";

  private static int [] zzUnpackAction() {
    int [] result = new int[236];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\44\0\110\0\44\0\154\0\44\0\44\0\220"+
    "\0\264\0\330\0\374\0\u0120\0\u0144\0\u0168\0\u018c\0\u01b0"+
    "\0\u01d4\0\u01f8\0\u021c\0\u0240\0\u0264\0\u0288\0\44\0\u02ac"+
    "\0\u02d0\0\u02f4\0\u0318\0\u033c\0\u0360\0\u0384\0\u03a8\0\u03cc"+
    "\0\u03f0\0\110\0\u0414\0\u0438\0\u045c\0\u0480\0\u04a4\0\u04c8"+
    "\0\u04ec\0\u0510\0\u0534\0\u0558\0\u057c\0\u05a0\0\u05c4\0\u05e8"+
    "\0\u060c\0\u0630\0\u0654\0\u0678\0\u069c\0\u06c0\0\u06e4\0\u0708"+
    "\0\u072c\0\u0750\0\u0774\0\u0798\0\44\0\u07bc\0\44\0\u07e0"+
    "\0\u0804\0\u0828\0\u084c\0\u0870\0\u0894\0\u08b8\0\u08dc\0\u0900"+
    "\0\u0924\0\u0948\0\u096c\0\u0990\0\u09b4\0\u09d8\0\u09fc\0\u0a20"+
    "\0\u0a44\0\u0a68\0\u0a8c\0\u0ab0\0\u0ad4\0\u0af8\0\u0b1c\0\u0b40"+
    "\0\u0b64\0\110\0\u0b88\0\u0bac\0\u0bd0\0\u0bf4\0\u0c18\0\u0c3c"+
    "\0\u0c60\0\110\0\u0c84\0\u0ca8\0\u0ccc\0\u0cf0\0\u0d14\0\110"+
    "\0\u0d38\0\u0d5c\0\u07e0\0\u0d80\0\u0da4\0\u0dc8\0\u0dec\0\u0e10"+
    "\0\u0e34\0\110\0\110\0\u0e58\0\u0e7c\0\u0ea0\0\u0ec4\0\u0ee8"+
    "\0\110\0\u0f0c\0\u0f30\0\110\0\u0f54\0\u0f78\0\u0f9c\0\u0fc0"+
    "\0\u0fe4\0\u1008\0\110\0\u102c\0\110\0\u1050\0\u1074\0\u1098"+
    "\0\110\0\u10bc\0\110\0\u10e0\0\u1104\0\u1128\0\u114c\0\u1170"+
    "\0\u1194\0\u11b8\0\u11dc\0\u1200\0\u1224\0\u1248\0\110\0\u126c"+
    "\0\u1290\0\u12b4\0\u12d8\0\u12fc\0\110\0\110\0\u1320\0\u1344"+
    "\0\110\0\u1368\0\u138c\0\110\0\u13b0\0\u13d4\0\110\0\u13f8"+
    "\0\u141c\0\u1440\0\u1464\0\u1488\0\u14ac\0\110\0\u14d0\0\110"+
    "\0\110\0\110\0\u14f4\0\u1518\0\u153c\0\u1560\0\u1584\0\u15a8"+
    "\0\u15cc\0\110\0\u15f0\0\u1614\0\110\0\u1638\0\110\0\u165c"+
    "\0\u1680\0\110\0\u16a4\0\110\0\110\0\u16c8\0\u16ec\0\110"+
    "\0\110\0\u1710\0\110\0\u1734\0\u1758\0\u177c\0\u17a0\0\u17c4"+
    "\0\u17e8\0\u180c\0\u1830\0\110\0\110\0\110\0\u1854\0\u1878"+
    "\0\u189c\0\u18c0\0\110\0\110\0\u18e4\0\u1908\0\u192c\0\110"+
    "\0\u1950\0\110\0\u1974\0\u1998\0\110\0\u19bc\0\110\0\110"+
    "\0\u19e0\0\110\0\u1a04\0\110";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[236];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\2\2\4\1\5\1\2\1\6\1\7"+
    "\1\10\1\3\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\3\1\21\1\22\3\3\1\23\1\24"+
    "\4\3\1\25\1\3\1\26\1\27\1\4\45\0\2\3"+
    "\6\0\30\3\10\0\1\30\1\31\36\0\2\3\6\0"+
    "\1\3\1\32\4\3\1\33\2\3\1\34\16\3\4\0"+
    "\2\3\6\0\11\3\1\35\1\36\3\3\1\37\11\3"+
    "\4\0\2\3\6\0\12\3\1\40\15\3\4\0\2\3"+
    "\6\0\14\3\1\41\4\3\1\42\1\3\1\43\4\3"+
    "\4\0\2\3\6\0\3\3\1\44\2\3\1\45\3\3"+
    "\1\46\4\3\1\47\10\3\4\0\2\3\6\0\2\3"+
    "\1\50\25\3\4\0\2\3\6\0\1\3\1\51\6\3"+
    "\1\52\5\3\1\53\1\54\6\3\1\55\1\3\4\0"+
    "\2\3\6\0\11\3\1\56\5\3\1\57\10\3\4\0"+
    "\2\3\6\0\13\3\1\60\14\3\4\0\2\3\6\0"+
    "\3\3\1\61\16\3\1\62\5\3\4\0\2\3\6\0"+
    "\1\3\1\63\4\3\1\64\4\3\1\65\14\3\4\0"+
    "\2\3\6\0\12\3\1\66\1\67\14\3\4\0\2\3"+
    "\6\0\3\3\1\70\1\71\1\3\1\72\3\3\1\73"+
    "\15\3\4\0\2\3\6\0\17\3\1\74\10\3\44\0"+
    "\1\75\2\0\3\30\1\76\1\77\37\30\6\100\1\101"+
    "\35\100\1\0\2\3\6\0\2\3\1\102\25\3\4\0"+
    "\2\3\6\0\5\3\1\103\22\3\4\0\2\3\6\0"+
    "\4\3\1\104\5\3\1\105\15\3\4\0\2\3\6\0"+
    "\13\3\1\106\14\3\4\0\2\3\6\0\12\3\1\107"+
    "\15\3\4\0\2\3\6\0\10\3\1\110\17\3\4\0"+
    "\2\3\6\0\14\3\1\111\13\3\4\0\2\3\6\0"+
    "\7\3\1\112\1\113\17\3\4\0\2\3\6\0\1\114"+
    "\27\3\4\0\2\3\6\0\6\3\1\115\21\3\4\0"+
    "\2\3\6\0\7\3\1\116\1\117\17\3\4\0\2\3"+
    "\6\0\14\3\1\120\13\3\4\0\2\3\6\0\6\3"+
    "\1\121\21\3\4\0\2\3\6\0\7\3\1\122\20\3"+
    "\4\0\2\3\6\0\1\123\27\3\4\0\2\3\6\0"+
    "\6\3\1\124\21\3\4\0\2\3\6\0\14\3\1\125"+
    "\13\3\4\0\2\3\6\0\12\3\1\126\15\3\4\0"+
    "\2\3\6\0\4\3\1\127\23\3\4\0\2\3\6\0"+
    "\1\3\1\130\4\3\1\131\7\3\1\132\11\3\4\0"+
    "\2\3\6\0\4\3\1\133\4\3\1\134\16\3\4\0"+
    "\2\3\6\0\10\3\1\135\17\3\4\0\2\3\6\0"+
    "\7\3\1\136\20\3\4\0\2\3\6\0\10\3\1\137"+
    "\17\3\4\0\2\3\6\0\3\3\1\140\24\3\4\0"+
    "\2\3\6\0\10\3\1\141\17\3\4\0\2\3\6\0"+
    "\26\3\1\142\1\3\4\0\2\3\6\0\1\3\1\143"+
    "\26\3\4\0\2\3\6\0\21\3\1\144\6\3\4\0"+
    "\2\3\6\0\12\3\1\145\15\3\4\0\2\3\6\0"+
    "\14\3\1\146\13\3\4\0\2\3\6\0\3\3\1\147"+
    "\24\3\4\0\2\3\6\0\11\3\1\150\16\3\4\0"+
    "\2\3\6\0\4\3\1\151\23\3\7\0\1\77\37\0"+
    "\6\100\1\152\42\100\1\153\1\152\35\100\1\0\2\3"+
    "\6\0\3\3\1\154\24\3\4\0\2\3\6\0\15\3"+
    "\1\155\12\3\4\0\2\3\6\0\25\3\1\156\2\3"+
    "\4\0\2\3\6\0\10\3\1\157\17\3\4\0\2\3"+
    "\6\0\6\3\1\160\21\3\4\0\2\3\6\0\3\3"+
    "\1\161\24\3\4\0\2\3\6\0\13\3\1\162\14\3"+
    "\4\0\2\3\6\0\24\3\1\163\3\3\4\0\2\3"+
    "\6\0\10\3\1\164\17\3\4\0\2\3\6\0\13\3"+
    "\1\165\14\3\4\0\2\3\6\0\3\3\1\166\6\3"+
    "\1\167\15\3\4\0\2\3\6\0\7\3\1\170\20\3"+
    "\4\0\2\3\6\0\13\3\1\171\14\3\4\0\2\3"+
    "\6\0\5\3\1\172\22\3\4\0\2\3\6\0\10\3"+
    "\1\173\17\3\4\0\2\3\6\0\11\3\1\174\16\3"+
    "\4\0\2\3\6\0\10\3\1\175\17\3\4\0\2\3"+
    "\6\0\13\3\1\176\14\3\4\0\2\3\6\0\10\3"+
    "\1\177\17\3\4\0\2\3\6\0\5\3\1\200\22\3"+
    "\4\0\2\3\6\0\11\3\1\201\16\3\4\0\2\3"+
    "\6\0\10\3\1\202\17\3\4\0\2\3\6\0\13\3"+
    "\1\203\14\3\4\0\2\3\6\0\14\3\1\204\13\3"+
    "\4\0\2\3\6\0\7\3\1\205\20\3\4\0\2\3"+
    "\6\0\12\3\1\206\1\207\14\3\4\0\2\3\6\0"+
    "\1\3\1\210\26\3\4\0\2\3\6\0\13\3\1\211"+
    "\14\3\4\0\2\3\6\0\13\3\1\212\14\3\4\0"+
    "\2\3\6\0\3\3\1\213\24\3\4\0\2\3\6\0"+
    "\4\3\1\214\23\3\4\0\2\3\6\0\2\3\1\215"+
    "\25\3\4\0\2\3\6\0\6\3\1\216\21\3\4\0"+
    "\2\3\6\0\6\3\1\217\21\3\4\0\2\3\6\0"+
    "\6\3\1\220\21\3\4\0\2\3\6\0\7\3\1\221"+
    "\20\3\4\0\2\3\6\0\3\3\1\222\24\3\3\0"+
    "\5\100\1\77\1\152\35\100\1\0\2\3\6\0\4\3"+
    "\1\223\23\3\4\0\2\3\6\0\6\3\1\224\21\3"+
    "\4\0\2\3\6\0\6\3\1\225\21\3\4\0\2\3"+
    "\6\0\13\3\1\226\14\3\4\0\2\3\6\0\15\3"+
    "\1\227\12\3\4\0\2\3\6\0\13\3\1\230\14\3"+
    "\4\0\2\3\6\0\6\3\1\231\21\3\4\0\2\3"+
    "\6\0\11\3\1\232\16\3\4\0\2\3\6\0\13\3"+
    "\1\233\14\3\4\0\2\3\6\0\11\3\1\234\16\3"+
    "\4\0\2\3\6\0\7\3\1\235\20\3\4\0\2\3"+
    "\6\0\17\3\1\236\10\3\4\0\2\3\6\0\4\3"+
    "\1\237\23\3\4\0\2\3\6\0\11\3\1\240\16\3"+
    "\4\0\2\3\6\0\11\3\1\241\16\3\4\0\2\3"+
    "\6\0\4\3\1\242\23\3\4\0\2\3\6\0\17\3"+
    "\1\243\10\3\4\0\2\3\6\0\10\3\1\244\17\3"+
    "\4\0\2\3\6\0\5\3\1\245\22\3\4\0\2\3"+
    "\6\0\7\3\1\246\20\3\4\0\2\3\6\0\26\3"+
    "\1\247\1\3\4\0\2\3\6\0\6\3\1\250\21\3"+
    "\4\0\2\3\6\0\11\3\1\251\16\3\4\0\2\3"+
    "\6\0\14\3\1\252\13\3\4\0\2\3\6\0\25\3"+
    "\1\253\2\3\4\0\2\3\6\0\3\3\1\254\24\3"+
    "\4\0\2\3\6\0\1\3\1\255\26\3\4\0\2\3"+
    "\6\0\10\3\1\256\17\3\4\0\2\3\6\0\3\3"+
    "\1\257\24\3\4\0\2\3\6\0\13\3\1\260\14\3"+
    "\4\0\2\3\6\0\13\3\1\261\14\3\4\0\2\3"+
    "\6\0\5\3\1\262\22\3\4\0\2\3\6\0\24\3"+
    "\1\263\3\3\4\0\2\3\6\0\10\3\1\264\17\3"+
    "\4\0\2\3\6\0\5\3\1\265\22\3\4\0\2\3"+
    "\6\0\6\3\1\266\21\3\4\0\2\3\6\0\14\3"+
    "\1\267\13\3\4\0\2\3\6\0\21\3\1\270\6\3"+
    "\4\0\2\3\6\0\23\3\1\271\4\3\4\0\2\3"+
    "\6\0\10\3\1\272\17\3\4\0\2\3\6\0\14\3"+
    "\1\273\13\3\4\0\2\3\6\0\6\3\1\274\21\3"+
    "\4\0\2\3\6\0\5\3\1\275\22\3\4\0\2\3"+
    "\6\0\11\3\1\276\16\3\4\0\2\3\6\0\17\3"+
    "\1\277\10\3\4\0\2\3\6\0\4\3\1\300\23\3"+
    "\4\0\2\3\6\0\20\3\1\301\7\3\4\0\2\3"+
    "\6\0\14\3\1\302\13\3\4\0\2\3\6\0\20\3"+
    "\1\303\7\3\4\0\2\3\6\0\13\3\1\304\14\3"+
    "\4\0\2\3\6\0\13\3\1\305\14\3\4\0\2\3"+
    "\6\0\3\3\1\306\24\3\4\0\2\3\6\0\3\3"+
    "\1\307\24\3\4\0\2\3\6\0\13\3\1\310\14\3"+
    "\4\0\2\3\6\0\13\3\1\311\14\3\4\0\2\3"+
    "\6\0\10\3\1\312\17\3\4\0\2\3\6\0\14\3"+
    "\1\313\13\3\4\0\2\3\6\0\5\3\1\314\22\3"+
    "\4\0\2\3\6\0\6\3\1\315\21\3\4\0\2\3"+
    "\6\0\13\3\1\316\14\3\4\0\2\3\6\0\1\3"+
    "\1\317\26\3\4\0\2\3\6\0\5\3\1\320\22\3"+
    "\4\0\2\3\6\0\12\3\1\321\15\3\4\0\2\3"+
    "\6\0\13\3\1\322\14\3\4\0\2\3\6\0\7\3"+
    "\1\323\20\3\4\0\2\3\6\0\7\3\1\324\20\3"+
    "\4\0\2\3\6\0\10\3\1\325\17\3\4\0\2\3"+
    "\6\0\16\3\1\326\11\3\4\0\2\3\6\0\13\3"+
    "\1\327\14\3\4\0\2\3\6\0\13\3\1\330\14\3"+
    "\4\0\2\3\6\0\5\3\1\331\22\3\4\0\2\3"+
    "\6\0\14\3\1\332\13\3\4\0\2\3\6\0\13\3"+
    "\1\333\14\3\4\0\2\3\6\0\10\3\1\334\17\3"+
    "\4\0\2\3\6\0\14\3\1\335\13\3\4\0\2\3"+
    "\6\0\14\3\1\336\13\3\4\0\2\3\6\0\6\3"+
    "\1\337\21\3\4\0\2\3\6\0\20\3\1\340\7\3"+
    "\4\0\2\3\6\0\12\3\1\341\15\3\4\0\2\3"+
    "\6\0\13\3\1\342\14\3\4\0\2\3\6\0\10\3"+
    "\1\343\17\3\4\0\2\3\6\0\4\3\1\344\23\3"+
    "\4\0\2\3\6\0\10\3\1\345\17\3\4\0\2\3"+
    "\6\0\21\3\1\346\6\3\4\0\2\3\6\0\21\3"+
    "\1\347\6\3\4\0\2\3\6\0\7\3\1\350\20\3"+
    "\4\0\2\3\6\0\27\3\1\351\4\0\2\3\6\0"+
    "\13\3\1\352\14\3\4\0\2\3\6\0\13\3\1\353"+
    "\14\3\4\0\2\3\6\0\20\3\1\354\7\3\3\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[6696];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\1\1\1\11\1\1\2\11\17\1\1\11"+
    "\1\1\1\0\43\1\1\11\1\1\1\11\2\0\50\1"+
    "\1\0\202\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[236];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
  private int contador; 


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Analizador(java.io.Reader in) {
         contador = 0; 
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Analizador(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 98) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Yytoken nextToken() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          zzR = false;
          break;
        case '\r':
          yyline++;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
          }
          break;
        default:
          zzR = false;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 8: 
          { /* ignore */
          }
        case 56: break;
        case 26: 
          { contador++; return new Yytoken(contador, yytext(), Simbolos.CATCH.toString(), yyline, yychar);
          }
        case 57: break;
        case 37: 
          { contador++; return new Yytoken(contador, yytext(), Simbolos.SWITCH.toString(), yyline, yychar);
          }
        case 58: break;
        case 35: 
          { contador++; return new Yytoken(contador, yytext(), Simbolos.IMPORT.toString(), yyline, yychar);
          }
        case 59: break;
        case 45: 
          { contador++; return new Yytoken(contador, yytext(), Simbolos.DEFAULT.toString(), yyline, yychar);
          }
        case 60: break;
        case 23: 
          { contador++; return new Yytoken(contador, yytext(), Simbolos.NULL.toString(), yyline, yychar);
          }
        case 61: break;
        case 6: 
          { contador++; return new Yytoken(contador, yytext(), Simbolos.EQ.toString(), yyline, yychar);
          }
        case 62: break;
        case 25: 
          { contador++; return new Yytoken(contador, yytext(), Simbolos.CLASS.toString(), yyline, yychar);
          }
        case 63: break;
        case 2: 
          { contador++; return new Yytoken(contador, yytext(), Simbolos.ID.toString(), yyline, yychar);
          }
        case 64: break;
        case 52: 
          { contador++; return new Yytoken(contador, yytext(), Simbolos.INSTANCEOF.toString(), yyline, yychar);
          }
        case 65: break;
        case 16: 
          { contador++; return new Yytoken(contador, yytext(), Simbolos.BYTE.toString(), yyline, yychar);
          }
        case 66: break;
        case 21: 
          { contador++; return new Yytoken(contador, yytext(), Simbolos.THIS.toString(), yyline, yychar);
          }
        case 67: break;
        case 49: 
          { contador++; return new Yytoken(contador, yytext(), Simbolos.PROTECTED.toString(), yyline, yychar);
          }
        case 68: break;
        case 10: 
          { contador++; return new Yytoken(contador, yytext(), Simbolos.DO.toString(), yyline, yychar);
          }
        case 69: break;
        case 14: 
          { contador++; return new Yytoken(contador, yytext(), Simbolos.NEW.toString(), yyline, yychar);
          }
        case 70: break;
        case 5: 
          { contador ++; return new Yytoken(contador, yytext(), Simbolos.CloseBracket.toString(), yyline, yychar);
          }
        case 71: break;
        case 30: 
          { contador++; return new Yytoken(contador, yytext(), Simbolos.FLOAT.toString(), yyline, yychar);
          }
        case 72: break;
        case 34: 
          { contador++; return new Yytoken(contador, yytext(), Simbolos.PUBLIC.toString(), yyline, yychar);
          }
        case 73: break;
        case 54: 
          { contador++; return new Yytoken(contador, yytext(), Simbolos.THREADSAFE.toString(), yyline, yychar);
          }
        case 74: break;
        case 28: 
          { contador++; return new Yytoken(contador, yytext(), Simbolos.SHORT.toString(), yyline, yychar);
          }
        case 75: break;
        case 18: 
          { contador++; return new Yytoken(contador, yytext(), Simbolos.CASE.toString(), yyline, yychar);
          }
        case 76: break;
        case 24: 
          { contador++; return new Yytoken(contador, yytext(), Simbolos.BREAK.toString(), yyline, yychar);
          }
        case 77: break;
        case 29: 
          { contador++; return new Yytoken(contador, yytext(), Simbolos.THROW.toString(), yyline, yychar);
          }
        case 78: break;
        case 17: 
          { contador++; return new Yytoken(contador, yytext(), Simbolos.LONG.toString(), yyline, yychar);
          }
        case 79: break;
        case 40: 
          { contador++; return new Yytoken(contador, yytext(), Simbolos.DOUBLE.toString(), yyline, yychar);
          }
        case 80: break;
        case 48: 
          { contador++; return new Yytoken(contador, yytext(), Simbolos.ABSTRACT.toString(), yyline, yychar);
          }
        case 81: break;
        case 47: 
          { contador++; return new Yytoken(contador, yytext(), Simbolos.CONTINUE.toString(), yyline, yychar);
          }
        case 82: break;
        case 39: 
          { contador++; return new Yytoken(contador, yytext(), Simbolos.NATIVE.toString(), yyline, yychar);
          }
        case 83: break;
        case 43: 
          { contador++; return new Yytoken(contador, yytext(), Simbolos.BOOLEAN.toString(), yyline, yychar);
          }
        case 84: break;
        case 12: 
          { contador++; return new Yytoken(contador, yytext(), Simbolos.INT.toString(), yyline, yychar);
          }
        case 85: break;
        case 19: 
          { contador++; return new Yytoken(contador, yytext(), Simbolos.CHAR.toString(), yyline, yychar);
          }
        case 86: break;
        case 15: 
          { contador++; return new Yytoken(contador, yytext(), Simbolos.FOR.toString(), yyline, yychar);
          }
        case 87: break;
        case 1: 
          { return new Yytoken(contador, yytext(), Simbolos.ERRO.toString(), yyline, yychar);
          }
        case 88: break;
        case 42: 
          { contador++; return new Yytoken(contador, yytext(), Simbolos.PRIVATE.toString(), yyline, yychar);
          }
        case 89: break;
        case 22: 
          { contador++; return new Yytoken(contador, yytext(), Simbolos.ELSE.toString(), yyline, yychar);
          }
        case 90: break;
        case 38: 
          { contador++; return new Yytoken(contador, yytext(), Simbolos.RETURN.toString(), yyline, yychar);
          }
        case 91: break;
        case 50: 
          { contador++; return new Yytoken(contador, yytext(), Simbolos.INTERFACE.toString(), yyline, yychar);
          }
        case 92: break;
        case 33: 
          { contador++; return new Yytoken(contador, yytext(), Simbolos.WHILE.toString(), yyline, yychar);
          }
        case 93: break;
        case 41: 
          { contador++; return new Yytoken(contador, yytext(), Simbolos.PACKAGE.toString(), yyline, yychar);
          }
        case 94: break;
        case 20: 
          { contador++; return new Yytoken(contador, yytext(), Simbolos.TRUE.toString(), yyline, yychar);
          }
        case 95: break;
        case 4: 
          { contador ++; return new Yytoken(contador, yytext(), Simbolos.OpenBracket.toString(), yyline, yychar);
          }
        case 96: break;
        case 11: 
          { contador++; return new Yytoken(contador, yytext(), Simbolos.EQEQ.toString(), yyline, yychar);
          }
        case 97: break;
        case 27: 
          { contador++; return new Yytoken(contador, yytext(), Simbolos.SUPER.toString(), yyline, yychar);
          }
        case 98: break;
        case 13: 
          { contador++; return new Yytoken(contador, yytext(), Simbolos.TRY.toString(), yyline, yychar);
          }
        case 99: break;
        case 51: 
          { contador++; return new Yytoken(contador, yytext(), Simbolos.TRANSIENT.toString(), yyline, yychar);
          }
        case 100: break;
        case 46: 
          { contador++; return new Yytoken(contador, yytext(), Simbolos.FINALLY.toString(), yyline, yychar);
          }
        case 101: break;
        case 32: 
          { contador++; return new Yytoken(contador, yytext(), Simbolos.FALSE.toString(), yyline, yychar);
          }
        case 102: break;
        case 7: 
          { contador++; return new Yytoken(contador, yytext(), Simbolos.PLUS.toString(), yyline, yychar);
          }
        case 103: break;
        case 44: 
          { contador++; return new Yytoken(contador, yytext(), Simbolos.EXTENDS.toString(), yyline, yychar);
          }
        case 104: break;
        case 9: 
          { contador++; return new Yytoken(contador, yytext(), Simbolos.IF.toString(), yyline, yychar);
          }
        case 105: break;
        case 53: 
          { contador++; return new Yytoken(contador, yytext(), Simbolos.IMPLEMENTS.toString(), yyline, yychar);
          }
        case 106: break;
        case 36: 
          { contador++; return new Yytoken(contador, yytext(), Simbolos.STATIC.toString(), yyline, yychar);
          }
        case 107: break;
        case 31: 
          { contador++; return new Yytoken(contador, yytext(), Simbolos.FINAL.toString(), yyline, yychar);
          }
        case 108: break;
        case 55: 
          { contador++; return new Yytoken(contador, yytext(), Simbolos.SYNCHRONIZED.toString(), yyline, yychar);
          }
        case 109: break;
        case 3: 
          { 
          }
        case 110: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
            return null;
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
