package lexico;
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FLOATING_POINT_LITERAL = 2;
  public static final int error = 1;
  public static final int FLOAT = 3;
  public static final int EOF = 0;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "FLOATING_POINT_LITERAL",
  "FLOAT"
  };
}

