
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Jun 07 09:23:13 BRT 2015
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface ParseSym {
  /* terminals */
  public static final int FLOATING_POINT_LITERAL = 2;
  public static final int error = 1;
  public static final int FLOAT = 3;
  public static final int EOF = 0;
}

