
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Jun 08 07:01:09 BRT 2015
//----------------------------------------------------

import java_cup.runtime.*;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Mon Jun 08 07:01:09 BRT 2015
  */
public class ParseCup extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public ParseCup() {super();}

  /** Constructor which sets the default scanner. */
  public ParseCup(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public ParseCup(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\002\000\002\002\003\000\002\002\004" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\004\000\004\012\005\001\002\000\004\002\006\001" +
    "\002\000\004\002\001\001\002\000\004\002\000\001\002" +
    "" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\004\000\004\002\003\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$ParseCup$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$ParseCup$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$ParseCup$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


 
  public void report_error(String message, Object info) {
    StringBuilder m = new StringBuilder("Error ");

    if (info instanceof java_cup.runtime.Symbol) 
      m.append( "("+info.toString()+")" );
     
    m.append(" : "+message);
   
    System.out.println(m);
  }
   
  public void report_fatal_error(String message, Object info) {
    report_error(message, info);
    throw new RuntimeException("Fatal Syntax Error");
  }

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$ParseCup$actions {
  private final ParseCup parser;

  /** Constructor */
  CUP$ParseCup$actions(ParseCup parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$ParseCup$do_action(
    int                        CUP$ParseCup$act_num,
    java_cup.runtime.lr_parser CUP$ParseCup$parser,
    java.util.Stack            CUP$ParseCup$stack,
    int                        CUP$ParseCup$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$ParseCup$result;

      /* select the action based on the action number */
      switch (CUP$ParseCup$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= floating_point_type EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$ParseCup$stack.elementAt(CUP$ParseCup$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$ParseCup$stack.elementAt(CUP$ParseCup$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$ParseCup$stack.elementAt(CUP$ParseCup$top-1)).value;
		RESULT = start_val;
              CUP$ParseCup$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$ParseCup$stack.elementAt(CUP$ParseCup$top-1)), ((java_cup.runtime.Symbol)CUP$ParseCup$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$ParseCup$parser.done_parsing();
          return CUP$ParseCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // floating_point_type ::= FLOAT 
            {
              Object RESULT =null;

              CUP$ParseCup$result = parser.getSymbolFactory().newSymbol("floating_point_type",0, ((java_cup.runtime.Symbol)CUP$ParseCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParseCup$stack.peek()), RESULT);
            }
          return CUP$ParseCup$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

